# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - MicroServicesApp3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Cambiar a 20.x para evitar problemas de compatibilidad con Newman

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Start API Server for testing
        run: |
          npm run start &
          sleep 10  # Esperar a que el servidor se inicie completamente
        env:
          PORT: 8080
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET || 'Microbus' }}
          
      - name: Run API tests with Newman
        run: npm run test:api:dev:report
        continue-on-error: false  # Si esto falla, detener el pipeline
        
      - name: Archive test results
        if: always()  # Ejecutar aunque el paso anterior falle
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: newman/*.html  # Ajusta la ruta donde se guardan los informes

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3D312DBB01A94F00B45493A79C7103AC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_69979DAA32A34AD0850471F3F8B6869D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D4D4C822089E403092083D6203C259C9 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MicroServicesApp3'
          slot-name: 'Production'
          package: .
          